[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl", "cargo", "pkg-config"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel setuptools-rust", "pip install -r requirements.txt"]
